MvcCoreAWSS3/Models/ErrorViewModel.cs
using System;

namespace MvcCoreAWSS3.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreAWSS3/Controllers/AwsFilesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MvcCoreAWSS3.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCoreAWSS3.Controllers
{
    public class AwsFilesController : Controller
    {
        private ServiceAWSS3 service;

        public AwsFilesController(ServiceAWSS3 service)
        {
            this.service = service;
        }

        public async Task<IActionResult> Index()
        {
            List<string> files = await this.service.GetFilesAsync();
            return View(files);
        }

        public IActionResult UploadFile()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UploadFile(IFormFile file)
        {
            using (Stream stream = file.OpenReadStream())
            {
                await this.service.UploadFileAsync(stream, file.FileName);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> FileAWS(string fileName)
        {
            Stream stream =
                await this.service.GetFileAsync(fileName);
            return File(stream, "image/png");
        }

        public async Task<IActionResult> Delete(string fileName)
        {
            await this.service.DeleteFileAsync(fileName);
            return RedirectToAction("Index");
        }
    }
}

MvcCoreAWSS3/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcCoreAWSS3.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCoreAWSS3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreAWSS3/Views/AwsFiles/Index.cshtml
@model List<string>

<h1 style="color:red">
    AWS Service S3
</h1>

<a asp-controller="AwsFiles"
   asp-action="UploadFile"
   class="btn btn-info">
    Upload File
</a>
<hr/>
@if (Model != null)
{
    <ul class="list-group">
        @foreach (string fileName in Model)
        {
            <li class="list-group-item">
                @fileName
                <a asp-controller="AwsFiles"
                   asp-action="FileAWS" class="btn btn-success"
                   asp-route-filename="@fileName">Ver fichero</a>
                <a asp-controller="AwsFiles" asp-action="Delete"
                   asp-route-filename="@fileName" class="btn btn-danger">
                    Eliminar
                </a>
            </li>
        }
    </ul>
}

MvcCoreAWSS3/Views/AwsFiles/UploadFile.cshtml
<h1 style="color:blue">
    Upload File AWS
</h1>

<form method="post" enctype="multipart/form-data">
    <label>Seleccione un fichero: </label>
    <input type="file" name="file" class="form-control"/>
    <button type="submit" class="btn btn-info">
        Upload File
    </button>
</form>

MvcCoreAWSS3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCoreAWSS3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreAWSS3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreAWSS3</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" 
                               asp-controller="AwsFiles" 
                               asp-action="Index">
                                Aws S3 Service
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcCoreAWSS3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>